swagger: '2.0'
info:
  title: REST API PATTOR
  version: 1.1.0
schemes:
  - https

paths:
  /patients:
    get:
      tags:
      - "patients"
      summary: "Get all patients"
      description: "Get all patients"
      operationId: "getAllPatients"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PatientsDto"
        400:
          description: "Invalid status value"
        500:
          description: "Internal server error"

  /doctors:
    get:
      tags:
      - "doctors"
      summary: "Get all doctors"
      description: "Get all doctors"
      operationId: "getAllDoctors"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/DoctorsDto"
        400:
          description: "Invalid status value"
        500:
          description: "Internal server error"