swagger: '2.0'
info:
  title: REST API PATTOR
  version: 1.1.0
schemes:
  - https

paths:
  ######################
  ###    Artboard    ###
  /artboards:
    post:
      summary: Add artboard with all components on it
      consumes:
        - application/json
      parameters:
        - name: artboard
          in: body
          required: true
          schema:
            $ref: './swagger-pattor-model.yaml#/definitions/ArtboardDto'
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
